### ISSUE TITLE
ValueError: Found two metrics with the same name: accuracy

### ISSUE THREAD

**Issue by sdxCool** [idrori/cu-ssp#2]
Sorry to interrupt.   I had problems running Mode1 and Model5.      “ValueError: Found two metrics with the same name: accuracy”. That's what I got wrong.    In terms of the runtime environment, I tried several, but I'll just list a few：

        1：python=3.8.3   keras=2.7.0    tensorflow=2.7.0(CPU)
        2：python=3.8.3   cudatoolkit=11.3.1   cudnn= 8.2.1   tensorflow-gpu=2.6.0(GPU)

As you can see, the same problem exists when running both environments.So, I can only botheryou, is it my environment or something else?Please answer, thank you.

**Comment by idrori** [comment]
All five models work fine. Btw: we use Github co-pilot or Codex nowadays for coding and setting up dependencies :)

**Comment by sdxCool** [comment]
> We use Github co-pilot or Codex nowadays for coding and setting up dependencies :)

Deer Mr.i, thank you for your reply. So you are saying that there is a problem with the environment. You cannot use Conda to configure the environment and Pycharm to run it?
